### ISSUE TITLE
No Keyboard and GApps Crash on Redmi 9C 

### ISSUE THREAD

**Issue by SaschaDMNGZ** [naz664/crDroid_patches#21]
Using A64 Binder32 GSI
• Google Apps keeps crashing - can't sign in
• No keyboard so I literally cannot type
• No File Manager app so I can't sideload apk

**Comment by Sp1ke47** [comment]
True. Just installed `crDroid-9.5-a64_bgN-Unofficial.img` on my Redmi 10A (code name dandelion, same as Redmi 9C) and found exactly the same problem.

1.  No built-in AOSP keyboard and file explorer so you have to install them manually via `adb`. 
2. "Google" keeps crashing, haven't figured out a solution.

I've sideloaded the arm64 gsi via DSU on another device and none of the problems above occurred. Hope they can be fixed soon.

**Comment by stephnradd** [comment]
This bug already present since early crDroid A13 builds by Naz. It happened because a64 version weirdly includes arm64 version of certain apps (including Gboard, Google App, Play Store, etc.)

The only workaround I find is to remove GApps manually and replace it with arm version or use bvn version and install arm version of GApps package instead.

**Comment by naz664** [comment]
Test now
Switched to Mindthegapps 
For more reference check this 
https://t.me/naz_dis/86227
