### ISSUE TITLE
About version 9.8

### ISSUE THREAD

**Issue by Tomushiki** [naz664/crDroid_patches#38]
Google setup wizard was misbehaving a bit
Also, when trying to login after screen goes of screen becomes unresponsive

**Comment by PinkSerenity** [comment]
Just adding something I have noticed in this kind of megathread:
While I haven't fully tested it (and haven't opened an issue because of this), at least on my slim build backups created by the Google Drive backup service can't be restored after factory resets (since the slim build doesn't have Google Setup Wizard, you need a different version or ROM for that). The error happens when entering the pin, it simply says: "An error has occurred." Though it's certainly also possible that it just happened to me and a weird constellation of corrupted data and unsuited ROM or something.
