### ISSUE TITLE
Signature spoofing

### ISSUE THREAD

**Issue by gitshoko** [naz664/crDroid_patches#54]
I've been trying out the vanilla version of crDroid 10 and been loving the features this rom provides.
However, without signature spoofing enabled, microG won't work on it.
Could you please add this feature so I can continue using this gsi?

**Comment by dragbeadle** [comment]
While I can manage without microG, I would like signature spoofing to be enabled again. According to the microG project, crDroid is supposed to support signature spoofing, see:

https://github.com/microg/GmsCore/wiki/Signature-Spoofing

Not sure if the issue is unique to this particular build or of crDroid has changed their policy regarding signature spoofing in Android 14. At the moment I can not lay my hand on a device running a supported version of crDroid 10 / Android 14, but I know someone who uses it, so maybe I'll check on their device. 

There may be workarounds using Magisk + LSPosed, but they do all sound rather hacky. Build in support for signature spoofing would be infinitely preferable.

**Comment by dragbeadle** [comment]
I can confirm that the official crDroid, version 10.1 /Android 14 does have signature spoofing enabled. Checked with someone who runs it on their Poco X5 Pro. 

So I expect adding signature spoofing should be possible for this GSI as well.

**Comment by dragbeadle** [comment]
On the newest 10.1 build signature spoofing works again. For me the issue is solved.
